In [11]:
import pandas as pd
import numpy as np

In [122]:
df = pd.read_csv("survey_data_cleaned.csv")
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,17,"Employed, full-time",Remote,Apples,Hobby,Primary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,39,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,Bachelors,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,49,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,Masters,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,21,"Student, full-time",NaN,Apples,NaN,College,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,21,"Student, full-time",NaN,Apples,NaN,Secondary school,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [13]:
df.shape

(65437, 114)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(15), int64(1), object(98)
memory usage: 56.9+ MB

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df_cleaned = df[['ResponseId', 'Age', 'Employment', 'RemoteWork', 'EdLevel', 
          'YearsCode', 'YearsCodePro', 'Country', 'LanguageHaveWorkedWith',
          'DatabaseHaveWorkedWith', 'PlatformHaveWorkedWith',
          'WebframeHaveWorkedWith', 'LanguageWantToWorkWith',
          'DatabaseWantToWorkWith', 'PlatformWantToWorkWith',
          'WebframeWantToWorkWith', 'CompTotal', 'ConvertedCompYearly', 
          'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8',
           'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'JobSat']].copy()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ResponseId              65437 non-null  int64
 1   Age                     65115 non-null  object
 2   Employment              65437 non-null  object
 3   RemoteWork              54806 non-null  object
 4   EdLevel                 60784 non-null  object
 5   YearsCode               59869 non-null  float64
 6   YearsCodePro            51610 non-null  float64
 7   Country                 58930 non-null  object
 8   LanguageHaveWorkedWith  59745 non-null  object
 9   DatabaseHaveWorkedWith  50254 non-null  object
 10  PlatformHaveWorkedWith  42366 non-null  object
 11  WebframeHaveWorkedWith  45161 non-null  object
 12  LanguageWantToWorkWith  55752 non-null  object
 13  DatabaseWantToWorkWith  42558 non-null  object
 14  PlatformWantToWorkWith  34532 non-null  object
 15  WebframeWantToWorkWith  38535 non-null  object
 16  CompTotal               33740 non-null  float64
 17  ConvertedCompYearly     23435 non-null  float64
 18  JobSatPoints_6          29450 non-null  float64
 19  JobSatPoints_7          29448 non-null  float64
 20  JobSatPoints_8          29456 non-null  float64
 21  JobSatPoints_9          29456 non-null  float64
 22  JobSatPoints_10         29450 non-null  float64
 23  JobSatPoints_11         29445 non-null  float64
 24  JobSat                  29126 non-null  float64
dtypes: float64(11), int64(1), object(13)
memory usage: 12.5+ MB

In [17]:
df_cleaned.head()

,ResponseId,Age,Employment,RemoteWork,EdLevel,YearsCode,YearsCodePro,Country,LanguageHaveWorkedWith,DatabaseHaveWorkedWith,...,WebframeWantToWorkWith,CompTotal,ConvertedCompYearly,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSat
0,1,17,"Employed, full-time",Remote,Primary school,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,39,"Employed, full-time",Remote,Bachelors,20.0,17.0,United Kingdom,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,...,Express;Htmx;Node.js;React;Remix,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,3,49,"Employed, full-time",Remote,Masters,37.0,27.0,United Kingdom,C#,Firebase Realtime Database,...,ASP.NET CORE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,21,"Student, full-time",NaN,College,4.0,NaN,Canada,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,MongoDB;MySQL;PostgreSQL;SQLite,...,jQuery;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,21,"Student, full-time",NaN,Secondary school,9.0,NaN,Norway,C++;HTML/CSS;JavaScript;Lua;Python;Rust,PostgreSQL;SQLite,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_cleaned['Age'].unique()

array(['17 ', '39 ', '49 ', '21 ', '29 ', '59 ', nan, '65 years or older'],
      dtype=object)

In [19]:
# Map Age categories to numeric values
age_map = {
    'Under 18 years old': 17,
    '18-24 years old': 21,
    '25-34 years old': 29.5,
    '35-44 years old': 39.5,
    '45-54 years old': 49.5,
    '55-64 years old': 59.5,
    '65 years or older': 70
}

df_cleaned['Age_num'] = df_cleaned['Age'].map(age_map)

In [20]:
df_cleaned['RemoteWork'].unique()

array(['Remote', nan, 'In-person', 'Hybrid'], dtype=object)

In [21]:
work_mapping = {'Hybrid (some remote, some in-person)': 'Hybrid'}

df_cleaned['RemoteWork'] = df_cleaned['RemoteWork'].replace(work_mapping)
display(df_cleaned['RemoteWork'].unique())

array(['Remote', nan, 'In-person', 'Hybrid'], dtype=object)

In [22]:
df_cleaned['EdLevel'].unique()

array(['Primary school', 'Bachelors', 'Masters', 'College',
       'Secondary school', 'Professional degree', 'Associate degree',
       'Something else', nan], dtype=object)

In [23]:
# Map messy education levels to simplified categories
edlevel_mapping = {
    "Bachelor’s degree (B.A., B.S., B.Eng., etc.)": "Bachelor",
    "Master’s degree (M.A., M.S., M.Eng., MBA, etc.)": "Master",
    "Professional degree (JD, MD, Ph.D, Ed.D, etc.)": "Doctorate",
    "Associate degree (A.A., A.S., etc.)": "Associate",
    "Some college/university study without earning a degree": "Some College",
    "Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)": "Secondary School",
    "Primary/elementary school": "Primary School",
    "Something else": "Other"
}

df_cleaned['EdLevel'] = df_cleaned['EdLevel'].map(edlevel_mapping)
display(df_cleaned['EdLevel'].unique())

array([nan, 'Other'], dtype=object)

In [24]:
df_cleaned['Country'].unique()

array(['United States', 'United Kingdom', 'Canada', 'Norway',
       'Uzbekistan', 'Serbia', 'Poland', 'Philippines', 'Bulgaria',
       'Switzerland', 'India', 'Germany', 'Ireland', 'Italy', 'Ukraine',
       'Australia', 'Brazil', 'Japan', 'Austria', 'Iran', 'France',
       'Saudi Arabia', 'Romania', 'Turkey', 'Nepal', 'Algeria', 'Sweden',
       'Netherlands', 'Croatia', 'Pakistan', 'Czech Republic',
       'North Macedonia', 'Finland', 'Slovakia', 'Russia', 'Greece',
       'Israel', 'Belgium', 'Mexico', 'Tanzania', 'Hungary', 'Argentina',
       'Portugal', 'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon',
       'Spain', 'South Africa', 'Lithuania', 'Viet Nam',
       'Dominican Republic', 'Indonesia', 'Kosovo', 'Morocco', 'Taiwan',
       'Georgia', 'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria',
       'Liechtenstein', 'Denmark', 'Ecuador', 'Malaysia', 'Albania',
       'Azerbaijan', 'Chile', 'Ghana', 'Peru', 'Bolivia', 'Egypt',
       'Luxembourg', 'Montenegro', 'Cyprus', 'Paraguay', 'Kazakhstan',
       'Slovenia', 'Jordan', 'Venezuela', 'Costa Rica', 'Jamaica',
       'Thailand', 'Nicaragua', 'Myanmar', 'South Korea', 'Rwanda',
       'Bosnia and Herzegovina', 'Benin', 'El Salvador', 'Zimbabwe',
       'Afghanistan', 'Estonia', 'Malta', 'Uruguay', 'Belarus',
       'Colombia', 'Republic of Moldova', 'Isle of Man', 'Nomadic',
       'New Zealand', 'Palestine', 'Armenia', 'United Arab Emirates',
       'Maldives', 'Ethiopia', 'Fiji', 'Guatemala', 'Uganda',
       'Turkmenistan', 'Mauritius', 'Kenya', 'Cuba', 'Gabon', 'Bahamas',
       'Iceland', 'Honduras', 'Hong Kong',
       "Lao People's Democratic Republic", 'Mongolia', 'Cambodia',
       'Madagascar', 'Angola', 'Democratic Republic of the Congo',
       'Syrian Arab Republic', 'Iraq', 'Namibia', 'Senegal', 'Kyrgyzstan',
       'Zambia', 'Swaziland', "C?e d'Ivoire", 'Kuwait', 'Tajikistan',
       'Burundi', 'Trinidad and Tobago', 'Mauritania', 'Sierra Leone',
       'Panama', 'Somalia', 'North Korea', 'Dominica', 'Guyana', 'Togo',
       'Oman', 'Barbados', 'Andorra', "Democratic People's South Korea",
       'Qatar', 'Sudan', 'Cameroon', 'Papua New Guinea', 'Bahrain',
       'Yemen', 'Malawi', 'Burkina Faso', 'Congo, Republic of the...',
       'Botswana', 'Guinea-Bissau', 'Mozambique',
       'Central African Republic', 'Equatorial Guinea', 'Suriname',
       'Belize', 'Libyan Arab Jamahiriya', 'Cape Verde',
       'Brunei Darussalam', 'Bhutan', 'Guinea', 'Niger',
       'Antigua and Barbuda', 'Mali', 'Samoa', 'Lesotho',
       'Saint Kitts and Nevis', 'Monaco',
       'Micronesia, Federated States of...', 'Haiti', nan, 'Nauru',
       'Liberia', 'Chad', 'Djibouti', 'Solomon Islands'], dtype=object)

In [25]:
# Standardized Country name
country_mapping = {
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'United States of America': 'United States',
    'Republic of North Macedonia': 'North Macedonia',
    'Russian Federation': 'Russia',
    'United Republic of Tanzania': 'Tanzania',
    'Iran, Islamic Republic of...': 'Iran',
    'Venezuela, Bolivarian Republic of...': 'Venezuela',
    'Hong Kong (S.A.R.)': 'Hong Kong',
    'Democratic Republic of the Congo': 'DR Congo',
    'Congo, Republic of the...': 'Congo (Republic)',
    'Viet Nam': 'Vietnam',
    'Republic of Korea': 'South Korea',
    "Lao People's Democratic Republic": 'Laos',
    'Syrian Arab Republic': 'Syria',
    "Democratic People's Republic of Korea": 'North Korea',
    'Micronesia, Federated States of...': 'Micronesia',
    'Libyan Arab Jamahiriya': 'Libya',
    'Republic of Moldova': 'Moldova'
}

df_cleaned['Country'] = df_cleaned['Country'].replace(country_mapping)
display(df_cleaned['Country'].unique())

array(['United States', 'United Kingdom', 'Canada', 'Norway',
       'Uzbekistan', 'Serbia', 'Poland', 'Philippines', 'Bulgaria',
       'Switzerland', 'India', 'Germany', 'Ireland', 'Italy', 'Ukraine',
       'Australia', 'Brazil', 'Japan', 'Austria', 'Iran', 'France',
       'Saudi Arabia', 'Romania', 'Turkey', 'Nepal', 'Algeria', 'Sweden',
       'Netherlands', 'Croatia', 'Pakistan', 'Czech Republic',
       'North Macedonia', 'Finland', 'Slovakia', 'Russia', 'Greece',
       'Israel', 'Belgium', 'Mexico', 'Tanzania', 'Hungary', 'Argentina',
       'Portugal', 'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon',
       'Spain', 'South Africa', 'Lithuania', 'Vietnam',
       'Dominican Republic', 'Indonesia', 'Kosovo', 'Morocco', 'Taiwan',
       'Georgia', 'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria',
       'Liechtenstein', 'Denmark', 'Ecuador', 'Malaysia', 'Albania',
       'Azerbaijan', 'Chile', 'Ghana', 'Peru', 'Bolivia', 'Egypt',
       'Luxembourg', 'Montenegro', 'Cyprus', 'Paraguay', 'Kazakhstan',
       'Slovenia', 'Jordan', 'Venezuela', 'Costa Rica', 'Jamaica',
       'Thailand', 'Nicaragua', 'Myanmar', 'South Korea', 'Rwanda',
       'Bosnia and Herzegovina', 'Benin', 'El Salvador', 'Zimbabwe',
       'Afghanistan', 'Estonia', 'Malta', 'Uruguay', 'Belarus',
       'Colombia', 'Moldova', 'Isle of Man', 'Nomadic', 'New Zealand',
       'Palestine', 'Armenia', 'United Arab Emirates', 'Maldives',
       'Ethiopia', 'Fiji', 'Guatemala', 'Uganda', 'Turkmenistan',
       'Mauritius', 'Kenya', 'Cuba', 'Gabon', 'Bahamas', 'Iceland',
       'Honduras', 'Hong Kong', 'Laos', 'Mongolia', 'Cambodia',
       'Madagascar', 'Angola', 'DR Congo', 'Syria', 'Iraq', 'Namibia',
       'Senegal', 'Kyrgyzstan', 'Zambia', 'Swaziland', "C?e d'Ivoire",
       'Kuwait', 'Tajikistan', 'Burundi', 'Trinidad and Tobago',
       'Mauritania', 'Sierra Leone', 'Panama', 'Somalia', 'North Korea',
       'Dominica', 'Guyana', 'Togo', 'Oman', 'Barbados', 'Andorra',
       "Democratic People's South Korea", 'Qatar', 'Sudan', 'Cameroon',
       'Papua New Guinea', 'Bahrain', 'Yemen', 'Malawi', 'Burkina Faso',
       'Congo (Republic)', 'Botswana', 'Guinea-Bissau', 'Mozambique',
       'Central African Republic', 'Equatorial Guinea', 'Suriname',
       'Belize', 'Libya', 'Cape Verde', 'Brunei Darussalam', 'Bhutan',
       'Guinea', 'Niger', 'Antigua and Barbuda', 'Mali', 'Samoa',
       'Lesotho', 'Saint Kitts and Nevis', 'Monaco', 'Micronesia',
       'Haiti', nan, 'Nauru', 'Liberia', 'Chad', 'Djibouti',
       'Solomon Islands'], dtype=object)

In [26]:
df_cleaned['YearsCodePro'].unique()

array([nan, 17., 27.,  7., 11., 25., 12., 10.,  3.,  0., 18., 37., 15.,
       20.,  6.,  2., 16.,  8., 14.,  4., 45.,  1., 24., 29.,  5., 30.,
       26.,  9., 33., 13., 35., 23., 22., 31., 19., 21., 28., 34., 32.,
       40., 50., 39., 44., 42., 41., 36., 38., 51., 43., 47., 48., 46.,
       49.])

In [27]:
yearcode_mapping = {'Less than 1 year': 0,
                'More than 50 years': 51}

df_cleaned['YearsCodePro'] = df_cleaned['YearsCodePro'].replace(yearcode_mapping)
display(df_cleaned['YearsCodePro'].unique())

array([nan, 17., 27.,  7., 11., 25., 12., 10.,  3.,  0., 18., 37., 15.,
       20.,  6.,  2., 16.,  8., 14.,  4., 45.,  1., 24., 29.,  5., 30.,
       26.,  9., 33., 13., 35., 23., 22., 31., 19., 21., 28., 34., 32.,
       40., 50., 39., 44., 42., 41., 36., 38., 51., 43., 47., 48., 46.,
       49.])

In [28]:
df_cleaned['YearsCode'] = df_cleaned['YearsCode'].replace(yearcode_mapping)
display(df_cleaned['YearsCode'].unique())

array([nan, 20., 37.,  4.,  9., 10.,  7.,  1., 15., 30., 31.,  6., 12.,
       22.,  5., 36., 25., 44., 24., 18.,  3.,  8., 51., 11., 29., 40.,
       39.,  2., 42., 34., 19., 35., 16., 33., 13., 23., 14., 28., 17.,
       21., 43., 46., 26., 32., 41., 45., 27., 38., 50., 48., 47.,  0.,
       49.])

In [29]:
df_cleaned['YearsCodePro'] = pd.to_numeric(df_cleaned['YearsCodePro'], errors='coerce')
df_cleaned['YearsCode'] = pd.to_numeric(df_cleaned['YearsCode'], errors='coerce')
df_cleaned['CompTotal'] = pd.to_numeric(df_cleaned['CompTotal'], errors='coerce')
df_cleaned['ConvertedCompYearly'] = pd.to_numeric(df_cleaned['ConvertedCompYearly'], errors='coerce')
df_cleaned['JobSatPoints_6'] = pd.to_numeric(df_cleaned['JobSatPoints_6'], errors='coerce')
df_cleaned['JobSatPoints_7'] = pd.to_numeric(df_cleaned['JobSatPoints_7'], errors='coerce')
df_cleaned['JobSatPoints_8'] = pd.to_numeric(df_cleaned['JobSatPoints_8'], errors='coerce')
df_cleaned['JobSatPoints_9'] = pd.to_numeric(df_cleaned['JobSatPoints_9'], errors='coerce')
df_cleaned['JobSatPoints_10'] = pd.to_numeric(df_cleaned['JobSatPoints_10'], errors='coerce')
df_cleaned['JobSatPoints_11'] = pd.to_numeric(df_cleaned['JobSatPoints_11'], errors='coerce')
df_cleaned['JobSat'] = pd.to_numeric(df_cleaned['JobSat'], errors='coerce')

In [30]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ResponseId              65437 non-null  int64
 1   Age                     65115 non-null  object
 2   Employment              65437 non-null  object
 3   RemoteWork              54806 non-null  object
 4   EdLevel                 932 non-null    object
 5   YearsCode               59869 non-null  float64
 6   YearsCodePro            51610 non-null  float64
 7   Country                 58930 non-null  object
 8   LanguageHaveWorkedWith  59745 non-null  object
 9   DatabaseHaveWorkedWith  50254 non-null  object
 10  PlatformHaveWorkedWith  42366 non-null  object
 11  WebframeHaveWorkedWith  45161 non-null  object
 12  LanguageWantToWorkWith  55752 non-null  object
 13  DatabaseWantToWorkWith  42558 non-null  object
 14  PlatformWantToWorkWith  34532 non-null  object
 15  WebframeWantToWorkWith  38535 non-null  object
 16  CompTotal               33740 non-null  float64
 17  ConvertedCompYearly     23435 non-null  float64
 18  JobSatPoints_6          29450 non-null  float64
 19  JobSatPoints_7          29448 non-null  float64
 20  JobSatPoints_8          29456 non-null  float64
 21  JobSatPoints_9          29456 non-null  float64
 22  JobSatPoints_10         29450 non-null  float64
 23  JobSatPoints_11         29445 non-null  float64
 24  JobSat                  29126 non-null  float64
 25  Age_num                 772 non-null    float64
dtypes: float64(12), int64(1), object(13)
memory usage: 13.0+ MB

In [33]:
#df_cleaned.to_csv('survey_data_cleaned.csv', index=False)

In [34]:
# Define multi-item columns
multi_item_columns = [
    'LanguageHaveWorkedWith',
    'DatabaseHaveWorkedWith',
    'PlatformHaveWorkedWith',
    'WebframeHaveWorkedWith',
    'LanguageWantToWorkWith',
    'DatabaseWantToWorkWith',
    'PlatformWantToWorkWith',
    'WebframeWantToWorkWith'
]

In [35]:
# Create reusable normalize function
def normalize_multivalue_column(df, column_name, id_col='ResponseId'):
    """
    Splits a semicolon-separated column into one row per value.
    """
    temp = df[[id_col, column_name]].dropna().copy()
    temp[column_name] = temp[column_name].str.split(';')
    temp = temp.explode(column_name)
    temp[column_name] = temp[column_name].str.strip()
    temp = temp[temp[column_name] != '']  # remove empty values
    return temp

In [36]:
# Normalize all multi-item columns
normalized_tables = {}

for col in multi_item_columns:
    normalized_tables[col] = normalize_multivalue_column(df_cleaned, col)

In [37]:
# Export all columns to csv file
for col, df_norm in normalized_tables.items():
    output_name = f"survey_{col.lower()}_normalized.csv"
    df_norm.to_csv(output_name, index=False)
    print(f"Saved: {output_name}")

Saved: survey_languagehaveworkedwith_normalized.csv
Saved: survey_databasehaveworkedwith_normalized.csv
Saved: survey_platformhaveworkedwith_normalized.csv
Saved: survey_webframehaveworkedwith_normalized.csv
Saved: survey_languagewanttoworkwith_normalized.csv
Saved: survey_databasewanttoworkwith_normalized.csv
Saved: survey_platformwanttoworkwith_normalized.csv
Saved: survey_webframewanttoworkwith_normalized.csv

In [38]:
# Export all demographic columns to csv file
demographic_columns = ['ResponseId', 'Age', 'EdLevel', 'Country']
df_demographics = df_cleaned[demographic_columns].copy()
df_demographics.to_csv('survey_demographics.csv', index=False)

In [44]:
df_cleaned.isnull().sum()

ResponseId                    0
Age                           0
Employment                    0
RemoteWork                10631
EdLevel                   64505
YearsCode                  5568
YearsCodePro              13827
Country                    6507
LanguageHaveWorkedWith     5692
DatabaseHaveWorkedWith    15183
PlatformHaveWorkedWith    23071
WebframeHaveWorkedWith    20276
LanguageWantToWorkWith     9685
DatabaseWantToWorkWith    22879
PlatformWantToWorkWith    30905
WebframeWantToWorkWith    26902
CompTotal                 31697
ConvertedCompYearly       42002
JobSatPoints_6            35987
JobSatPoints_7            35989
JobSatPoints_8            35981
JobSatPoints_9            35981
JobSatPoints_10           35987
JobSatPoints_11           35992
JobSat                    36311
Age_num                   64665
dtype: int64

In [129]:
#filled the column "Age" using mean

Age1 = df_cleaned["Age"].mean

df_cleaned["Age"] =df_cleaned["Age"].fillna(Age1)

In [139]:
#filled the column "RemoteWork" using mode

RemoteWork1 = df_cleaned["RemoteWork"].mode()[0]

df_cleaned["RemoteWork"] = df_cleaned["RemoteWork"].fillna(RemoteWork1)

In [140]:
#filled the column "EdLevel" using mode

EdLevel1 = df_cleaned["EdLevel"].mode()[0]

df_cleaned["EdLevel"] = df_cleaned["EdLevel"].fillna(EdLevel1)

In [141]:
#filled the column "YearsCode" using median

YearsCode1 = df_cleaned["YearsCode"].median

df_cleaned["YearsCode"] = df_cleaned["YearsCode"].fillna(YearsCode1)

In [142]:
#filled the column "YearsCodePro" using median

YearsCodePro1 = df_cleaned["YearsCodePro"].median

df_cleaned["YearsCodePro"] = df_cleaned["YearsCodePro"].fillna(YearsCodePro1)

In [143]:
#filled the column "Country" using mode

Country1 = df["Country"].mode()[0]

df_cleaned["Country"] = df_cleaned["Country"].fillna(Country1)

In [144]:
#filled the column "CompTotal" using forward fill and the remaing missing values using median

df_cleaned["CompTotal"] = df_cleaned["CompTotal"].ffill()

CopmTotal1 = df_cleaned["CompTotal"].median()

df_cleaned["CompTotal"] = df_cleaned["CompTotal"].fillna(CompTotal1)

In [145]:
#filled the column "ConvertedCompYearly" using mean

CompYearly = df_cleaned["ConvertedCompYearly"].mean()

df_cleaned["ConvertedCompYearly"] = df_cleaned["ConvertedCompYearly"].fillna(CompYearly)

In [146]:
#filled the columns "JobSat" and "JobSatPoints" using Forward fill

df_cleaned["JobSatPoints_6"] = df_cleaned["JobSatPoints_6"].ffill()
df_cleaned["JobSatPoints_7"] = df_cleaned["JobSatPoints_7"].ffill()
df_cleaned["JobSatPoints_8"] = df_cleaned["JobSatPoints_8"].ffill()
df_cleaned["JobSatPoints_9"] = df_cleaned["JobSatPoints_9"].ffill()
df_cleaned["JobSatPoints_10"] = df_cleaned["JobSatPoints_10"].ffill()
df_cleaned["JobSatPoints_11"] = df_cleaned["JobSatPoints_11"].ffill()
df_cleaned["JobSat"] = df_cleaned["JobSat"].ffill()

In [147]:
#filled the column "LanguageHaveWorkedWith" and "LanguageWantToWorkWith" using mode

lang1 = df_cleaned["LanguageHaveWorkedWith"].mode()[0]

df_cleaned["LanguageHaveWorkedWith"] =df_cleaned["LanguageHaveWorkedWith"].fillna(lang1)

lang2 = df_cleaned["LanguageWantToWorkWith"].mode()[0]

df_cleaned["LanguageWantToWorkWith"] =df_cleaned["LanguageWantToWorkWith"].fillna(lang2)

In [148]:
#filled the column "DatabaseHaveWorkedWith" and "DatabaseWantToWorkWith" using mode

dat1 = df_cleaned["DatabaseHaveWorkedWith"].mode()[0]

df_cleaned["DatabaseHaveWorkedWith"] =df_cleaned["DatabaseHaveWorkedWith"].fillna(dat1)

dat2 = df_cleaned["DatabaseWantToWorkWith"].mode()[0]

df_cleaned["DatabaseWantToWorkWith"] =df_cleaned["DatabaseWantToWorkWith"].fillna(dat2)

In [149]:
#filled the column "PlatformHaveWorkedWith" and "PlatformWantToWorkWith" using mode

plat1 = df_cleaned["PlatformHaveWorkedWith"].mode()[0]

df_cleaned["PlatformHaveWorkedWith"] =df_cleaned["PlatformHaveWorkedWith"].fillna(plat1)

plat2 = df_cleaned["PlatformWantToWorkWith"].mode()[0]

df_cleaned["PlatformWantToWorkWith"] =df_cleaned["PlatformWantToWorkWith"].fillna(plat2)

In [150]:
#filled the column "WebframeHaveWorkedWith" and "WebframeWantToWorkWith" using mode

web1 = df_cleaned["WebframeHaveWorkedWith"].mode()[0]

df_cleaned["WebframeHaveWorkedWith"] =df_cleaned["WebframeHaveWorkedWith"].fillna(web1)

web2 = df_cleaned["WebframeWantToWorkWith"].mode()[0]

df_cleaned["WebframeWantToWorkWith"] =df_cleaned["WebframeWantToWorkWith"].fillna(web2)

In [159]:
df_cleaned.isnull().sum()

ResponseId                    0
Age                           0
Employment                    0
RemoteWork                    0
EdLevel                       0
YearsCode                     0
YearsCodePro                  0
Country                       0
LanguageHaveWorkedWith        0
DatabaseHaveWorkedWith        0
PlatformHaveWorkedWith        0
WebframeHaveWorkedWith        0
LanguageWantToWorkWith        0
DatabaseWantToWorkWith        0
PlatformWantToWorkWith        0
WebframeWantToWorkWith        0
CompTotal                     0
ConvertedCompYearly           0
JobSatPoints_6                1
JobSatPoints_7                1
JobSatPoints_8                1
JobSatPoints_9                1
JobSatPoints_10               1
JobSatPoints_11               1
JobSat                       10
Age_num                   64665
dtype: int64

In [ ]:

df["ConvertedCompYearly_Log"] = np.log1p(df["ConvertedCompYearly"])

In [ ]:
df["ConvertedCompYearly_MinMax"] = df["ConvertedCompYearly"].value_counts(normalize = True)